name: workflow

on:
    push:
        branches:
            - main
        paths-ignore:
            - 'README.md'

jobs:
    integration:
        name: continous integration
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Lint Code
              run: echo "Lintint repository"

            - name: run unit tests
              run: echo "Running unit tests"
